# Generated by Django 3.0.7 on 2020-07-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videorequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videotitile',
            field=models.CharField(max_length=30),
        ),
    ]
