# Generated by Django 3.0.7 on 2020-07-07 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videorequest', '0002_auto_20200707_0754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='videotitile',
            new_name='videotitle',
        ),
    ]
